#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generate an .env file with random secrets for a named stack.
#
# Usage:
#   ./generate-env.sh <type>          # writes .env.<type> (won't overwrite)
#   ./generate-env.sh <type> --force  # overwrites existing file
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TYPE="${1:-}"

if [ -z "$TYPE" ]; then
    echo "Usage: $0 <type> [--force]"
    echo ""
    echo "Generates .env.<type> with random secrets."
    echo "Example: $0 prod"
    exit 1
fi

ENV_FILE="$SCRIPT_DIR/.env.${TYPE}"

if [ -f "$ENV_FILE" ] && [ "${2:-}" != "--force" ]; then
    echo "Error: $ENV_FILE already exists."
    echo "Use --force to overwrite, or edit it directly."
    exit 1
fi

secret() { openssl rand -base64 "$1" | tr -d '\n/+='; }

cat > "$ENV_FILE" <<EOF
# Generated by generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit this file.

# ── Database ────────────────────────────────────────────────
POSTGRES_PASSWORD=$(secret 32)

# ── Backend ─────────────────────────────────────────────────
JWT_SECRET_KEY=$(secret 48)

# ── Forgejo (git backend) ──────────────────────────────────
FORGEJO_ADMIN_PASSWORD=$(secret 32)
FORGEJO_WEBHOOK_SECRET=$(secret 32)
EOF

chmod 600 "$ENV_FILE"
echo "Generated $ENV_FILE"
