#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generate a .env.prod file with random secrets.
#
# Usage:
#   ./generate-env.sh              # writes .env.prod (won't overwrite)
#   ./generate-env.sh --force      # overwrites existing .env.prod
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.prod"

if [ -f "$ENV_FILE" ] && [ "${1:-}" != "--force" ]; then
    echo "Error: $ENV_FILE already exists."
    echo "Use --force to overwrite, or edit it directly."
    exit 1
fi

secret() { openssl rand -base64 "$1" | tr -d '\n/+='; }

cat > "$ENV_FILE" <<EOF
# Generated by generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do NOT commit this file.

# ── Database ────────────────────────────────────────────────
POSTGRES_PASSWORD=$(secret 32)

# ── Backend ─────────────────────────────────────────────────
OPENAI_API_KEY=
JWT_SECRET_KEY=$(secret 48)

# ── Forgejo (git backend) ──────────────────────────────────
FORGEJO_ADMIN_PASSWORD=$(secret 32)
FORGEJO_WEBHOOK_SECRET=$(secret 32)

# ── Verification Service ────────────────────────────────────
VERIFY_API_KEY=$(secret 32)
EOF

chmod 600 "$ENV_FILE"
echo "Generated $ENV_FILE"
echo "Remember to fill in OPENAI_API_KEY before deploying."
